Vagrant.configure(2) do |config|
  config.vm.box = "CentOS7"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "ansible" do |ansible|
  
    ansible.playbook = "provisioning/site.yml"
    ansible.inventory_path = "provisioning/hosts"
    ansible.limit = 'all'
    
  end
  
  config.vm.synced_folder "../20_www", "/usr/share/nginx/html", owner: "vagrant", group: "vagrant", mount_options: ['dmode=777','fmode=755']

end
