Vagrant.configure(2) do |config|
  config.vm.box = "CentOS7"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box 
  end
    
  config.vm.network "private_network", ip: "192.168.33.10"
  
  
#  config.ssh.private_key_path = ".vagrant/machines/default/virtualbox/private_key"

  config.vm.provision "ansible_local" do |ansible|
  
    ansible.playbook = "provisioning/site.yml"
    ansible.install        = true
#    ansible.verbose        = "vvvv"
    #ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
    ansible.inventory_path = "provisioning/hosts"
    ansible.limit          = "all"
    
  end
  
  config.vm.synced_folder "../20_www", "/usr/share/nginx/html", owner: "vagrant", group: "vagrant", mount_options: ['dmode=777','fmode=755']

end
